projetoHerlon/projetoHerlon.Web/Models/ModelLogin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace projetoHerlon.Web.Models
{
    public class ModelLogin
    {
        public string Usuario { get; set; }
        public string Senha { get; set; }
    }
}

projetoHerlon/projetoHerlon.Web/Models/ModelTeste.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace projetoHerlon.Web.Models
{
    public class ModelTeste
    {

        public ModelTeste()
        {
            NomeTeste = nameof(this.NomeTeste);
        }
        [Display(Name = "Label Teste")]
        public string NomeTeste { get; set; }
    }
}

projetoHerlon/projetoHerlon.Web/Controllers/AcessoController.cs
using projetoHerlon.Dominio.Repositorios;
using projetoHerlon.Dominio.Util;
using projetoHerlon.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace projetoHerlon.Web.Controllers
{
    public class AcessoController : Controller
    {
        private IRepositorioFireBase _Firebase = IoC.Resolver<IRepositorioFireBase>();

        [HttpGet]
        public ActionResult Logon()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Logon(ModelLogin login)
        {
            try
            {
                

                if (login.Senha != null && login.Usuario != null)
                {
                    var temp = _Firebase.Login(login.Usuario, login.Senha);
                    if (temp != null )
                    {
                        Session["Usuario"] = temp.User.DisplayName;
                        Session["Foto"] = temp.User.PhotoUrl;
                    }


                    return RedirectToAction("Index", "Home", new { id = "OK" });
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                throw ex.InnerException;
            }
           
        }
    }
}

projetoHerlon/projetoHerlon.Web/Controllers/CadastroController.cs
using projetoHerlon.Dominio.Repositorios;
using projetoHerlon.Dominio.Util;
using projetoHerlon.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projetoHerlon.Web.Controllers
{
    public class CadastroController : Controller
    {
        private IRepositorioFireBase _Firebase = IoC.Resolver<IRepositorioFireBase>();

        [HttpGet]
        public ActionResult CadastrarUsuario()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CadastrarUsuario(ModelCriarConta CriarConta)
        {
            try
            {
                if (CriarConta.Email != null && CriarConta.Senha != null && _Firebase.CriarNovoUsuario(CriarConta.Email, CriarConta.Senha,$"{CriarConta.Nome} {CriarConta.Sobrenome}"))
                {
                    var temp = _Firebase.Login(CriarConta.Email, CriarConta.Senha);
                    if (temp != null)
                    {
                        Session["Usuario"] = temp.User.DisplayName;
                        Session["Foto"] = temp.User.PhotoUrl;

                        return RedirectToAction("Index", "Home", new { id = "OK" });
                    }
                    return View();
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
    }
}

projetoHerlon/projetoHerlon.Web/Controllers/HomeController.cs
using Newtonsoft.Json;
using projetoHerlon.Dominio.ObjetoDominio;
using projetoHerlon.Dominio.Repositorios;
using projetoHerlon.Dominio.Util;
using projetoHerlon.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projetoHerlon.Web.Controllers
{
    public class HomeController : Controller
    {
        private IRepositorioTeste2 _repositorioTeste = IoC.Resolver<IRepositorioTeste2>();

        private IRepositorioFireBase _FB = IoC.Resolver<IRepositorioFireBase>();
        private IRepositorioCep _CEP = IoC.Resolver<IRepositorioCep>();



        public ActionResult Index(string id)
        {

            if (Config.Debug)
            {
                //_CEP.ConverterListaParaJson(@"C:\Users\DELL\Desktop\ceps.txt", @"C:\Users\DELL\Desktop\ceps.json");
                //var lista = _CEP.ListaDeCeps(@"C:\Users\DELL\Desktop\ceps.json");
                var watch = System.Diagnostics.Stopwatch.StartNew();
                var lista = _CEP.PesquisarCep(@"C:\Users\DELL\Desktop\ceps.json", "32410330");
                watch.Stop();
                var elapsedMs = watch.ElapsedMilliseconds;



                //_FB.CriarNovoUsuario("asdasdtestea@hotmail.com", "meuzovo", "Herlon", "nulo");

                var authlink = _FB.Login("herlon_vk@hotmail.com", "meuzovo");

                var temp = _FB.GetFB(authlink.FirebaseToken, authlink.User.LocalId);
                if (temp == "null" || temp == "\"\"")
                {
                    Config.Message(_FB.CriarNovaBaseUsuario(authlink.FirebaseToken, authlink.User.LocalId));
                }

                _FB.AdicionarNovoConjugue(authlink.FirebaseToken, authlink.User.LocalId);


                var Reader = _FB.GetFB(authlink.FirebaseToken, authlink.User.LocalId);

                string json = "";

                if (Reader != "null")
                {
                    var jsonDs = JsonConvert.DeserializeObject<ClasseNovoUsuario>(Reader);
                    if (jsonDs != null && jsonDs._Clientes.Count < 5)
                    {
                        _FB.AdicionarNovoCliente(authlink.FirebaseToken, authlink.User.LocalId);
                        _FB.AdicionarNovoCliente(authlink.FirebaseToken, authlink.User.LocalId);
                    }
                }

                string conj = "nulo";
                _FB.AdicionarNovoClienteConjugue(authlink.FirebaseToken, authlink.User.LocalId, conj);
                _FB.AdicionarNovoClienteCliente(authlink.FirebaseToken, authlink.User.LocalId, conj);

                conj = "123";
                _FB.AdicionarNovoClienteConjugue(authlink.FirebaseToken, authlink.User.LocalId, conj);
                _FB.AdicionarNovoClienteCliente(authlink.FirebaseToken, authlink.User.LocalId, conj);

                _FB.ReordenarClientes(authlink.FirebaseToken, authlink.User.LocalId);

                var authlink2 = _FB.Login("cliente@vendedor.com.br", "Cliente que vende!!!");

                temp = _FB.GetFB(authlink.FirebaseToken, authlink.User.LocalId);
                if (temp == "null")
                {
                    Config.Message(_FB.CriarNovoUsuario("cliente@vendedor.com.br", "Cliente que vende!!!", "Sem Nome", "nulo2").ToString());
                }


                //EM TRABALHO!!!!
                //Config.Message(_FB.AssociarBaseUsuarioCliente(authlink.FirebaseToken, authlink.User.LocalId, "nulo", authlink2.FirebaseToken, authlink2.User.LocalId).ToString());
            }
            if (id == "OK")
            {
                return View();
            }
            else
            {
                return Redirect("~/Acesso/Logon");
            }

        }

        public ActionResult About(ModelTeste model)
        {
            var retorno = _repositorioTeste.MetodoTeste(model.NomeTeste);
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

projetoHerlon/projetoHerlon.Web/Views/Acesso/Logon.cshtml
@model projetoHerlon.Web.Models.ModelLogin
@{
    Layout = "";
}

<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-md-3"></div>
                            <div class="col-md-6 card o-hidden border-0 shadow-lg my-5">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bem Vindo!</h1>
                                    </div>
                                    @using (Html.BeginForm())
                                    {
                                        <div class="form-group">
                                            @Html.TextBoxFor(model => model.Usuario, new { @class = "form-control form-control-user", placeholder = "Entre com seu Email..." })
                                        </div>
                                        <div class="form-group">
                                            @Html.TextBoxFor(model => model.Senha, new { @type = "password", @class = "form-control form-control-user", placeholder = "Senha" })
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Me lembrar</label>
                                            </div>
                                        </div>

                                        <button type="submit" class="btn btn-primary btn-user btn-block" value="Entrar" id="btnLogin" name="btnLogin">Entrar</button>
                                        <p class="alert-warning" style="display:none" id="alertUsuario">Por favor insira o usuario</p>
                                        <p class="alert-warning" style="display:none" id="alertSenha">Por favor insira a senha</p>
                                        <!--
                                        <a href="#" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Entrar com o Google
                                        </a>
                                            -->
                                    }
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="#">Esqueceu a senha?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("CadastrarUsuario","Cadastro")">Crie uma conta!</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>



    <!-- Bootstrap core JavaScript-->
    <script src="~/Scripts/jquery.min.js"></script>
    @*<script src="~/Scripts/bootstrap.bundle.min.js"></script>*@

    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Scripts/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    @*<script src="~/Scripts/Chart.min.js"></script>*@

    <!-- Page level custom scripts -->
    <script src="~/Scripts/chart-area-demo.js"></script>
    <script src="~/Scripts/chart-pie-demo.js"></script>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")

    <script>
        $("#btnLogin").click(function () {
            if ($("#Usuario").val() == "" || $("#Usuario").val() == undefined) {
                $("#alertUsuario").css("display", "block");
                return false;
            } else {
                $("#alertUsuario").css("display", "none");
            }

            if ($("#Senha").val() == "" || $("#Senha").val() == undefined) {
                $("#alertSenha").css("display", "block");
                return false;
            } else {
                $("#alertSenha").css("display", "none");
            }
            return true;
        })
    </script>
</body>

</html>

projetoHerlon/projetoHerlon.Web/Views/Cadastro/CadastrarUsuario.cshtml
@model projetoHerlon.Web.Models.ModelCriarConta
@{
    Layout = "";
}

<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cadastrar Usuario</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-md-12 card o-hidden border-0 shadow-lg my-5">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Crie uma conta!</h1>
                                    </div>
                                    @using (Html.BeginForm())
                                    {
                                        <form class="user">
                                            <div class="form-group row">
                                                <div class="col-sm-6 mb-3 mb-sm-0">
                                                    @Html.TextBoxFor(model => model.Nome, new { @class = "form-control form-control-user", @id = "exampleFirstName", placeholder = "Nome" })
                                                </div>
                                                <div class="col-sm-6">
                                                    @Html.TextBoxFor(model => model.Sobrenome, new { @class = "form-control form-control-user", @id = "exampleLastName", placeholder = "Sobrenome" })
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                @Html.TextBoxFor(model => model.Email, new { @type = "email", @class = "form-control form-control-user", @id = "exampleInputEmail", placeholder = "Email" })
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-6 mb-3 mb-sm-0">
                                                    @Html.TextBoxFor(model => model.Senha, new { @type = "password", @class = "form-control form-control-user", @id = "exampleInputPassword", placeholder = "Senha" })
                                                </div>
                                                <div class="col-sm-6">
                                                    @Html.TextBoxFor(model => model.Senha, new { @type = "password", @class = "form-control form-control-user", @id = "exampleRepeatPassword", placeholder = "Senha" })
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary btn-user btn-block" value="Salvar conta" id="btnSalvarConta" name="btnSalvarConta">Salvar conta</button>
                                            <hr>
                                        </form>
                                    }
                                    <hr>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>



    <!-- Bootstrap core JavaScript-->
    <script src="~/Scripts/jquery.min.js"></script>
    @*<script src="~/Scripts/bootstrap.bundle.min.js"></script>*@

    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Scripts/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    @*<script src="~/Scripts/Chart.min.js"></script>*@

    <!-- Page level custom scripts -->
    <script src="~/Scripts/chart-area-demo.js"></script>
    <script src="~/Scripts/chart-pie-demo.js"></script>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")


</body>

</html>

projetoHerlon/projetoHerlon.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

projetoHerlon/projetoHerlon.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

projetoHerlon/projetoHerlon.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

<ul>
    <div>

    </div>
</ul>